version: '3'
services:
  zed-app:
    build: .
    runtime: nvidia
    privileged: true
    volumes:
      - .:/app
    environment:
      - DISPLAY=$DISPLAY
      - NVIDIA_DRIVER_CAPABILITIES=all
    devices:
      - /dev/video0:/dev/video0
