[workspace]
members = [
  "radar_device",
  "dataflow_example/node",
  "dataflow_example/operator",
  "dataflow_example/sink",
  "dataflow_example/orchestrator",
  "dora/orchestrator",
  "dora/aggregator",
  "dora/radar_client"
]

[workspace.package]
version = "0.1.0"

[workspace.dependencies]
dora-node-api = "0.3.0"
dora-operator-api = "0.3.0"
dora-daemon = "0.3.0"
dora-core = "0.3.0"
dora-coordinator = "0.3.0"
dora-cli = "0.3.0"
