[workspace]
members = [
  "ti_device",
  "server",
  "radars",
  "client",
  "zed_device",
  "visualiser"
]

[workspace.package]
version = "0.1.0"

[workspace.dependencies]
dora-node-api = "0.3.0"
dora-operator-api = "0.3.0"
dora-daemon = "0.3.0"
