# Use the Stereolabs ZED SDK runtime image
FROM stereolabs/zed:4.0-devel-cuda12.1-ubuntu22.04

# Set the working directory
WORKDIR /app

# (Optional) Install additional dependencies or perform other setup tasks
# RUN apt-get update && apt-get install -y [your-dependencies]

# (Optional) Copy your application files into the container
# COPY . /app

# Command to run when starting the container
CMD ["/bin/bash"]
