name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix build .#packages.x86_64-linux.mmwave-dashboard
      - run: nix build .#packages.x86_64-linux.mmwave-machine
      - run: nix build .#packages.x86_64-linux.mmwave-discovery
