name: Upload Release Asset

on:
  push:
    branches:
    - main
jobs:
  build:
    name: Build and Release Binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - uses: cachix/cachix-action@v14
        with:
          name: mycache
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .#packages.x86_64-linux.aarch64-linux.mmwave-dashboard
      - run: nix build .#packages.x86_64-linux.aarch64-linux.mmwave-machine
      - run: nix build .#packages.x86_64-linux.aarch64-linux.mmwave-discover
